title: Fitness Adventure Travel Vacations
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.4910394
  brandStrength: 0.5
  lightness: 0.5645161
  brandColors:
    - '#2A0318'
    - '#F1F0D2'
    - '#83151C'
    - '#B55938'
    - '#DD9548'
  rhythmicContrast: 0.5
cta:
  bucket: null
  version: null
  domain: null
name: Just-In-Boston
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.49906
layout_spectrum: 0.51045
