name: Just-In-Boston
favicon: null
layout_spectrum: 0.49352
typography_spectrum: 0.52938
title: Fitness Adventure Travel Vacations
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#042b7f'
    - '#369716'
    - '#94d27f'
    - '#7789a9'
  brandStrength: 0.5
  lightness: 0.5830536261200905
  saturation: 0.5930247511714697
  rhythmicContrast: 0.26734712393954396
purpose: []
